add_rules("mode.debug", "mode.release")

set_languages("c++20")
add_defines("GLOG_USE_GLOG_EXPORT")

includes("src/phoenix_mcp/xmake.lua")

add_requires("vcpkg::reflectcpp 0.22.0")
add_requires("vcpkg::yyjson")
add_requires("vcpkg::spdlog")
add_requires("crow")
add_requires("vcpkg::folly")
add_requires("vcpkg::glog")
add_requires("vcpkg::gflags")
add_requires("vcpkg::boost-context")
add_requires("vcpkg::libevent")
add_requires("vcpkg::double-conversion")
add_requires("vcpkg::drogon")
add_requires("vcpkg::trantor")
add_requires("vcpkg::jsoncpp")
add_requires("vcpkg::openssl")
add_requires("vcpkg::brotli")
add_requires("vcpkg::zlib")
add_requires("vcpkg::libuuid")
add_requires("vcpkg::c-ares")

target("PhoenixMcp")
    set_default(false)
    set_kind("binary")
    add_deps("phoenix_mcp")
    add_files("src/*.cpp")
    add_packages("vcpkg::reflectcpp", "vcpkg::yyjson", "vcpkg::spdlog", "crow", "vcpkg::folly", "vcpkg::glog", "vcpkg::gflags", "vcpkg::boost-context", "vcpkg::libevent", "vcpkg::double-conversion", "vcpkg::drogon", "vcpkg::trantor", "vcpkg::jsoncpp", "vcpkg::openssl", "vcpkg::brotli", "vcpkg::zlib", "vcpkg::libuuid", "vcpkg::c-ares")

target("using_tool_registry")
    set_default(false)
    set_kind("binary")
    add_deps("phoenix_mcp")
    add_files("examples/using_tool_registry/*.cpp")
    add_includedirs("src")
    add_packages("vcpkg::reflectcpp", "vcpkg::yyjson", "vcpkg::spdlog", "crow", "vcpkg::folly", "vcpkg::glog", "vcpkg::gflags", "vcpkg::boost-context", "vcpkg::libevent", "vcpkg::double-conversion", "vcpkg::drogon", "vcpkg::trantor", "vcpkg::jsoncpp", "vcpkg::openssl", "vcpkg::brotli", "vcpkg::zlib", "vcpkg::libuuid", "vcpkg::c-ares")

target("create_server")
    set_default(false)
    set_kind("binary")
    add_deps("phoenix_mcp")
    add_files("examples/create_server/*.cpp")
    add_includedirs("src")
    add_packages("vcpkg::reflectcpp", "vcpkg::yyjson", "vcpkg::spdlog", "crow", "vcpkg::folly", "vcpkg::glog", "vcpkg::gflags", "vcpkg::boost-context", "vcpkg::libevent", "vcpkg::double-conversion", "vcpkg::drogon", "vcpkg::trantor", "vcpkg::jsoncpp", "vcpkg::openssl", "vcpkg::brotli", "vcpkg::zlib", "vcpkg::libuuid", "vcpkg::c-ares")

target("create_server_http")
    set_default(false)
    set_kind("binary")
    add_deps("phoenix_mcp")
    add_files("examples/create_server_http/*.cpp")
    add_includedirs("src")
    add_packages("vcpkg::reflectcpp", "vcpkg::yyjson", "vcpkg::spdlog", "crow", "vcpkg::folly", "vcpkg::glog", "vcpkg::gflags", "vcpkg::boost-context", "vcpkg::libevent", "vcpkg::double-conversion", "vcpkg::drogon", "vcpkg::trantor", "vcpkg::jsoncpp", "vcpkg::openssl", "vcpkg::brotli", "vcpkg::zlib", "vcpkg::libuuid", "vcpkg::c-ares")
