#ifndef PHOENIX_MCP_PRIVATE_TOOL_REGISTRY_UTILS_HPP_
#define PHOENIX_MCP_PRIVATE_TOOL_REGISTRY_UTILS_HPP_

#include "phoenix_mcp/tool_registry/utils.h"

#endif  // PHOENIX_MCP_PRIVATE_TOOL_REGISTRY_UTILS_HPP_
