include_guard(GLOBAL)

function(phoenix_mcp_enable_warnings target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4)
    if(PHOENIX_MCP_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(PHOENIX_MCP_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
  endif()
endfunction()
